---
abstract: 'maintain and search a minimal CPAN database'
author:
  - 'Serguei Trouchelle <stro@cpan.org>'
build_requires:
  CPAN::HandleConfig: '0'
  CPAN::Version: '0'
  Carp: '0'
  DBD::SQLite: '0'
  ExtUtils::MakeMaker: '0'
  File::Copy: '0'
  File::Spec: '0'
  FindBin: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Scalar::Util: '0'
  Test::More: '0.94'
  base: '0'
  lib: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.037, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CPAN-SQLite
requires:
  CPAN: '0'
  CPAN::DistnameInfo: '0'
  Compress::Zlib: '0'
  Cwd: '0'
  DBI: '0'
  English: '0'
  Exporter: '0'
  File::Basename: '0'
  File::Find: '0'
  File::HomeDir: '0'
  File::Path: '0'
  File::Spec: '0'
  File::Spec::Functions: '0'
  Getopt::Long: '0'
  HTTP::Tiny: '0'
  Safe: '0'
  constant: '0'
  parent: '0'
  strict: '0'
  utf8: '0'
  warnings: '0'
version: '0.211'
